#!/bin/sh

# PROVIDE: late-start
# REQUIRE: slim

PATH=$PATH:/usr/sbin
export PATH

. /etc/rc.subr

name="late"
start_cmd="${name}_start"

extra_commands="disable_early_services"
disable_early_services_cmd="${name}_disable_early_services"

# NOTE: devd needs to stay enabled in early boot
# so that we have a working mouse pointer as soon as Xorg is started

SERVICES="setup-mouse webcamd vboxservice dsbdriverd netif routing defaultroute avahi-daemon clear-tmp cupsd ntpdate smartd sshd"

late_start()
{
    service devd restart # For networking; invokes dhcpd
    for SERVICE in $SERVICES ; do
        service "$SERVICE" onestart
    done
}

late_disable_early_services()
{
    for SERVICE in $SERVICES ; do
        service "$SERVICE" disable
    done
}

load_rc_config $name
run_rc_command "$1"
