#!/bin/sh

# PROVIDE: localize
# REQUIRE: ldconfig
# KEYWORD: nojail shutdown

PATH=$PATH:/usr/local/sbin:/usr/local/bin
export PATH

. /etc/rc.subr

name="localize"
start_cmd="${name}_start"

localize_start()
{
    # /usr/local/bin/update-desktop-database # TODO: Move somewhere else (this has nothing to do with localize but needs to run)
    /usr/local/sbin/localize
}

load_rc_config $name
run_rc_command "$1"
