#!/rescue/sh
#
# $FreeBSD$
#

# PROVIDE: live
# BEFORE: var
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="live"
desc="Mount read-write union filesystems to create a Live system"
start_cmd="${name}_start"

live_start()
{

  if [ "$(kenv live_enable)" != "YES" ] ; then
    exit 0
  fi

  echo "XXXXXXXXXXXXXXXXXXX UNION XXXXXXXXXXXXXXXXXXXXXXXXX"
  set -x
  
  umount -uw /

  kldload geom_uzip

  mkdir -p /tmp
  mdmfs -s 512m md97 /tmp
  chmod a+rwx /tmp # So that Chrome can start

  mkdir -p /tmp/union

  # TODO: Use DIRS=$(find  /* \! -name . -prune -type d) but clean it
  DIRS="/Applications /bin /lib /libexec /sbin /System /root /etc" # /var
  # FIXME: Having added /etc to the above results in 30 extra seconds related to the default route...
  # var will make initgfx crash X once; but maybe that's just initgx at work?
  for DIR in $DIRS; do
    mkdir -p /tmp/union/rw$DIR
    mount -t unionfs /tmp/union/rw$DIR $DIR
  done
  
  mdmfs -s 256m md98 /var # Without this, rc.d/var leads to reboot?
  chmod a+rwx /var # Will this help???

  DIRS="local bin sbin include lib lib32 libdata libexec obj ports share src tests"
  for DIR in $DIRS; do
    mkdir -p /tmp/union/rwusr/$DIR
    mount -t unionfs /tmp/union/rwusr/$DIR /usr/$DIR
  done
  
  # unionfs-nullfs for /usr/home leads to crashes when trying to use Chromium
  mkdir -p /usr/home
  mdmfs -s 256m md99 /usr/home
 
}

run_rc_command "$1"
