#!/rescue/sh

# Silence messages if boot_mute="YES" is set
if [ "$(kenv boot_mute)" = "YES" ] ; then
        exec 1>>/dev/null 2>&1
fi

if [ "$SINGLE_USER" = "true" ]; then
        echo "Starting interactive shell in /etc/rc of the ramdisk..."
        exit 0
fi

set -x

if [ "$(kenv use_unionfs)" = "YES" ] ; then
  echo "==> We should never end up here"
  exit 0
else
  if [ ! -e /dev/md2 ] ; then
    halt -p
  fi
  echo "==> Ramdisk /etc/rc running"
  echo "==> Unset rescue init kernel environment variables"
  kenv -u init_chroot
  kenv -u init_path
  kenv -u init_script
  kenv -u init_shell
  echo "==> Unmount filesystems for cloning"
  umount -f /livecd/dev
  zpool export livecd
  zpool export furybsd || true
  umount -f /cdrom
  echo "==> Set /dev/md2 device for reroot"
  kenv vfs.root.mountfrom=zfs:livecd
  echo "==> Rerooting into memdisk"
  reboot -r
fi
