#!/rescue/sh

# Silence messages if boot_mute="YES" is set
if [ "$(kenv boot_mute)" = "YES" ] ; then
        exec 1>>/dev/null 2>&1
fi

if [ "$SINGLE_USER" = "true" ]; then
        echo "Starting interactive shell in /etc/rc of the ramdisk..."
        exit 0
fi

set -x

if [ "$(kenv use_unionfs)" = "YES" ] ; then
  echo "==> Ramdisk /etc/rc running"

  # umount -f /cdrom
  # kenv init_chroot # Hopefully the system will continue booting from that location after this script exits with 0
  kenv -u init_chroot
  kenv -u init_path
  kenv -u init_script
  kenv -u init_shell
  
  echo "==> XXXXXXXXXXXXXXXXXXX UNION XXXXXXXXXXXXXXXXXXXXXXXXX"

  umount -uw /
  
  kldload  /usr/local/furybsd/uzip/boot/kernel/nullfs.ko

  # TODO: Use DIRS=$(find  /* \! -name . -prune -type d) but clean it
  DIRS="/Applications /bin /lib /libexec /sbin /System /root /etc" # /var
  # FIXME: Having added /etc to the above results in 30 extra seconds related to the default route...
  # var will make initgfx crash X once; but maybe that's just initgx at work?
  for DIR in $DIRS; do
    mkdir -p /tmp/union/rw$DIR $DIR
    mount -t nullfs /usr/local/furybsd/uzip$DIR $DIR
    mount -t unionfs /tmp/union/rw$DIR $DIR
  done
  
  mdmfs -s 256m md98 /var # Without this, rc.d/var leads to reboot
  chmod a+rwx /var # Will this help???

   DIRS="local bin sbin include lib lib32 libdata libexec obj ports share src tests"
   for DIR in $DIRS; do
     mkdir -p /tmp/union/rwusr/$DIR /usr/$DIR
     mount -t nullfs /usr/local/furybsd/uzip/usr/$DIR /usr/$DIR
     mount -t unionfs /tmp/union/rwusr/$DIR /usr/$DIR
   done
  
   # unionfs-nullfs for /usr/home leads to crashes when trying to use Chromium
   mkdir -p /usr/home
   mdmfs -s 256m md99 /usr/home
   cp -r -p /usr/local/furybsd/uzip/usr/home/* /usr/home/
 
   chmod a+rwx /tmp # So that Chrome can start
  exit 0
else
  if [ ! -e /dev/md2 ] ; then
    halt -p
  fi
  echo "==> Ramdisk /etc/rc running"
  echo "==> Unset rescue init kernel environment variables"
  kenv -u init_chroot
  kenv -u init_path
  kenv -u init_script
  kenv -u init_shell
  echo "==> Unmount filesystems for cloning"
  umount -f /livecd/dev
  zpool export livecd
  zpool export furybsd || true
  umount -f /cdrom
  echo "==> Set /dev/md2 device for reroot"
  kenv vfs.root.mountfrom=zfs:livecd
  echo "==> Rerooting into memdisk"
  reboot -r
fi
